services:
  - type: web
    name: dragon-ball-game-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    buildCommand: ""
    startCommand: ""
    rootDir: backend
    autoDeploy: true
    region: oregon
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:Iu9jkKFkOvFcaCtV3ZRuhdkx+PjV3Q2ShiObMQa3sCQ=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: nozomi.proxy.rlwy.net
      - key: DB_PORT
        value: 13143
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: bSteYWZpyzAAFmOIPzuuTBrIPKGTWCHw
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
